### ISSUE TITLE
 Can not find method:“System.String SAPbobsCOM.ICompany.get_SecurityCode()”

### ISSUE THREAD

**Issue by zh3305** [shockzinfinity/sapHowmuch.Base#7]
Build and run sapHowmuch.Base.TestWinForm on sbo 9.2 PL07 (9.20.170) 32-bit ,Win2008R2 sp1 Error:
I can not find the cause of the error
   {System.MissingMethodException: Can not find method:“System.String SAPbobsCOM.ICompany.get_SecurityCode()”。
   in  sapHowmuch.Base.SapHowmuchAddonContext..ctor()
   in  sapHowmuch.Base.TestWinform.TestWinformContext..ctor() location Z:\sap\SAP FrameWork\sapHowmuch.Base\sapHowmuch.Base.TestWinform\TestWinformContext.cs:Line 13
   in  sapHowmuch.Base.TestWinform.Program.Main() location Z:\sap\SAP FrameWork\sapHowmuch.Base\sapHowmuch.Base.TestWinform\Program.cs:Line 22}

**Comment by shockzinfinity** [comment]
{SAPbobsCOM.ICompany.get_SecurityCode() error} is actually caused of SAPbobsCOM SDK library.

I couldn't know why its getter property error in SAPbobsCOM SDK, just comment **'sapHowmuchLogger.Trace' part in 'SapHowmuchAddonContext.cs:Line 33'**

Thanks your feedback
